# ===== НАСТРОЙКИ БАЗЫ ДАННЫХ =====
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=Mds200208801
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== НАСТРОЙКИ JPA/HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== НАСТРОЙКИ ЛОГИРОВАНИЯ =====
logging.level.com.project.userService=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===== НАСТРОЙКИ СЕРВЕРА =====
server.port=8080
server.servlet.context-path=/
